### ISSUE TITLE
 Error message: file not found.

### ISSUE THREAD

**Issue by alebersol** [btimofeev/lazy_ips#2]
No matter what rom I try to patch, it gives me this error message, when I push the execute button:

File not found.

Do not understand, since in the selection dialog, the rom file is there.

**Comment by hadess** [comment]
It says "File not found" for any I/O errors:
https://github.com/btimofeev/lazy_ips/blob/master/lazy_ips.py#L117

The file you're trying to modify is likely read-only or not writable. Tick the "backup" box.

**Comment by alebersol** [comment]
OHHHHH BOY!!! I'm red ashamed. You are right... The file permissions were wrong...

SORRY, SORRY, SORRY, in capital letters.

And thank you for your quick response.

Best regards,

**Comment by btimofeev** [comment]
Thanks to everyone, I probably need to change the error message.

ср, 13 нояб. 2019 г., 15:00 alebersol <notifications@github.com>:
