### ISSUE TITLE
Cut official releases

### ISSUE THREAD

**Issue by ainola** [btimofeev/lazy_ips#4]
As a packager, it would be helpful to have releases as tarballs. I see that you have version numbers in a text file but that makes it rather awkward to package. Would you be open to using Github's releases functionality instead?

Thanks!

**Comment by btimofeev** [comment]
Ok, I will post it on the release page. https://github.com/btimofeev/lazy_ips/archive/v20191208.tar.gz

I also added an installation script, so now the program needs to be installed with the command `python setup.py install --root="$pkgdir/"` and set `setuptools` as make dependency (example for ArchLinux https://wiki.archlinux.org/index.php/Python_package_guidelines). This command will automatically create the necessary scripts in `/usr/bin`
